name: 🐞 Bug Report
description: Report a bug or unexpected behavior in Tasky
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below clearly.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what went wrong.
      placeholder: The task list disappears when refreshing the page...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Explain how we can reproduce the issue step-by-step.
      placeholder: |
        1. Go to "Add Task"
        2. Create a task
        3. Refresh the page
        4. Task disappears
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Mention your environment info (browser, OS, etc.)
      placeholder: e.g., Chrome 118 / Windows 11
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: Paste or drag screenshots/logs here if available.
