name: 💡 Feature Request
description: Suggest a new idea or feature for Tasky
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! Please describe your suggestion clearly.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your request related to a problem? Describe it.
      placeholder: I'd like Tasky to automatically sort tasks by priority...
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Explain your proposed solution or feature.
      placeholder: Add a sorting dropdown menu in the task list.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered other alternatives or workarounds?
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any additional information, screenshots, or sketches here.
